### ISSUE TITLE
IOError: Morphology not found at 'simple.swc'

### ISSUE THREAD

**Issue by SvennoNito** [BlueBrain/BluePyOpt#229]
Hey,
I've managed to run BluePyOpt and Neuron on a Linux Cluster and I'm very excited to work with it! Using the example you provide [here](https://github.com/BlueBrain/BluePyOpt/blob/master/examples/simplecell/simplecell.ipynb), (I basically just copy pasted everything) I get the following error:

```
responses = twostep_protocol.run(cell_model=simple_cell, param_values=default_params, sim=nrn) 

Exception: Traceback (most recent call last):
  File "/cm/shared/uniol/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/bluepyopt/ephys/protocols.py", line 130, in _run_func
    cell_model.instantiate(sim=sim)
  File "/cm/shared/uniol/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/bluepyopt/ephys/models.py", line 222, in instantiate
    self.morphology.instantiate(sim=sim, icell=self.icell)
  File "/cm/shared/uniol/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/bluepyopt/ephys/morphologies.py", line 91, in instantiate
    self.morphology_path)
IOError: Morphology not found at 'simple.swc'
```

Do you know how I can check where 'simple.swc' is stored and how I can tell python to grap it?

**Comment by wvangeit** [comment]
Hi,
Great to here that you're using our software.
That morphology is located here:
https://github.com/BlueBrain/BluePyOpt/blob/master/examples/simplecell/simple.swc

I assume the easiest way is to download the file and put it in the same directory from where you run your script.

If you want to do it automatically, let me know, I will provide some code snippet on how to download it from python

**Comment by SvennoNito** [comment]
Great, thanks for the quick reply! Doing so throws a different error:

```
Exception: Traceback (most recent call last):
  File "/cm/shared/uniol/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/bluepyopt/ephys/protocols.py", line 130, in _run_func
    cell_model.instantiate(sim=sim)
  File "/cm/shared/uniol/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/bluepyopt/ephys/models.py", line 222, in instantiate
    self.morphology.instantiate(sim=sim, icell=self.icell)
  File "/cm/shared/uniol/software/Python/2.7.12-intel-2016b/lib/python2.7/site-packages/bluepyopt/ephys/morphologies.py", line 114, in instantiate
    imorphology.input(str(self.morphology_path))
RuntimeError: hoc error
```

**Comment by wvangeit** [comment]
Is there any more info on your screen  from the error ? This is basically NEURON throwing an error, normal it shows a bit more output.

Which system are you using / which version of NEURON ?

**Comment by SvennoNito** [comment]
I downloaded the html instead of the .swc  file of simple.swc (stupid me). I copied the entries into the file instead and now it is working. Thanks for your guidance!

**Comment by wvangeit** [comment]
Ok, np. Good to hear that it works now 👍
